<x-main>
    <div class="relative px-6 lg:px-8 bg-gradient-to-b from-sky-200 to-white ">
        <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
            <div class="text-center">
                <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Simple Things Are Hard</h1>
                <p class="mt-6 text-lg leading-8 text-gray-600">Welcome. Here I aim to showcase some of my work, experience, and thoughts.</p>
                <div class="mt-10 flex items-center justify-center gap-x-6">
                    <a href="#" class="rounded-md bg-sky-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-sky-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600">About Me</a>
                    <a href="#" class="text-base font-semibold leading-7 text-gray-900">Learn more <span aria-hidden="true">→</span></a>
                </div>
            </div>
        </div>
    </div>
    <div>
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
        lorem ipsum
    </div>
</x-main>

